- We are getting this error "java.lang.NoSuchMethodError:org.keycloak.representations.idm.RoleRepresentation.setScopeParamRequired(Ljava/lang/Boolean;)V" because at runtime appformer is calling method setScopeParamRequired in keycloak-core with a primitive boolean, while the method itself accept a Boolean wrapper type.is the 1st commit message: - Added Boolean wrapper type as method argument. - written test cases for creating group in sso using keycloak.